# Generated by Django 6.0.2 on 2026-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_full_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('complexity_score', models.FloatField(default=0.0)),
                ('language_distribution', models.JSONField(default=dict)),
                ('module_depth', models.IntegerField(default=0)),
                ('contributor_count', models.IntegerField(default=0)),
                ('average_pr_size', models.FloatField(default=0.0)),
                ('activity_score', models.FloatField(default=0.0)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('topics', models.JSONField(default=list)),
                ('primary_language', models.CharField(blank=True, max_length=100)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
