# Generated by Django 6.0.2 on 2026-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100, unique=True)),
                ('experience_score', models.FloatField(default=0.0)),
                ('skill_level', models.FloatField(default=1.0)),
                ('domain_keywords', models.JSONField(default=list)),
                ('languages', models.JSONField(default=dict)),
                ('total_repos', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('total_prs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
