# Generated by Django 6.0.2 on 2026-02-19 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_issue_number', models.IntegerField()),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('labels', models.JSONField(default=list)),
                ('comment_count', models.IntegerField(default=0)),
                ('difficulty_score', models.FloatField(default=0.0)),
                ('is_good_first_issue', models.BooleanField(default=False)),
                ('is_bug', models.BooleanField(default=False)),
                ('linked_pr_size', models.FloatField(default=0.0)),
                ('resolution_time_days', models.FloatField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True)),
                ('state', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='repositories.repository')),
            ],
            options={
                'unique_together': {('repository', 'github_issue_number')},
            },
        ),
    ]
