# Generated by Django 6.0.2 on 2026-02-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('pr_url', models.URLField()),
                ('pr_difficulty', models.FloatField()),
                ('skill_before', models.FloatField()),
                ('skill_after', models.FloatField()),
                ('growth_factor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
